<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ZD-104CCR3" failures="1" tests="2" name="/Users/vn5485h/Downloads/RunnerTestSuite" time="49.441" errors="0" timestamp="2023-01-18T13:17:23 IST">
  <testcase classname="com.zee.backend.TestWebNetworkCalls" name="test01_Validate_GA_And_Scorecard_Request_AfterOpeningTheArticle_For_Web" time="25.239"/>
  <testcase classname="com.zee.backend.TestWebNetworkCalls" name="test02_Validate_GA_With_IncorrectTID_And_Scorecard_Request_AfterOpeningTheArticle_For_Web" time="19.391">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verified, TID Attribute value of GA Calls expected [UA-2069755-112] but found [UA-2069755-1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Verified, TID Attribute value of GA Calls expected [UA-2069755-112] but found [UA-2069755-1]
at com.zee.backend.TestWebNetworkCalls.test02_Validate_GA_With_IncorrectTID_And_Scorecard_Request_AfterOpeningTheArticle_For_Web(TestWebNetworkCalls.java:115)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test02_Validate_GA_With_IncorrectTID_And_Scorecard_Request_AfterOpeningTheArticle_For_Web -->
</testsuite> <!-- /Users/vn5485h/Downloads/RunnerTestSuite -->
